### ISSUE TITLE
Class 'App\Traits\XeroAPI\XeroPHP\Api\AccountingApi' not found

### ISSUE THREAD

**Issue by chirag2324** [XeroAPI/xero-php-oauth2#87] opened 2020-03-24 11:47 UTC
**SDK you're using (please complete the following information):**
 - Version [e.g. 1.4]

**Describe the bug**
Class 'App\Traits\XeroAPI\XeroPHP\Api\AccountingApi' not found

AccoutingApi class is found in your library but when I use it can't be defined. 

**To Reproduce**

Just type the AccoutingApi class name for any IDE which provides an auto-complete feature.

**Expected behavior**
Class 'App\Traits\XeroAPI\XeroPHP\Api\AccountingApi' not found

**Screenshots**
![Whoops  There was an error1 ](https://user-images.githubusercontent.com/55869433/77422371-5b08b800-6df3-11ea-89d9-e7766b4cf5b8.png)

**Comment by SidneyAllen** [comment] 2020-03-24 16:22
@chirag2324 

I'm sorry this issue doesn't appear to be directly related to the Xero SDK.  Based on your screenshot this is related to its use with the Symphony framework.

If you are able to resolve this and can share your solution that might help others in the community.

I'll be closing this issue as it isn't something we can solve for.

**Closed by SidneyAllen** 2020-03-24 16:22 UTC
Labels: Status: Wontfix, Type: Dependencies

**Comment by chirag2324** [comment] 2020-03-25 03:18
@SidneyAllen I am using laravel framework. I follow all steps which you defined in your package installation. Please guide me my work is stuck.

**Comment by SidneyAllen** [comment] 2020-03-25 16:12
@chirag2324 - we don't offer support for use of our SDKs in conjunction with other frameworks, but a developer in the community has a project that helps them integrate xero-php-oauth2 and laravel.

https://github.com/webfox/laravel-xero-oauth2

**Comment by mmehmet** [comment] 2020-06-01 06:32
I can confirm I also have this problem - it appears to be because this one single class is over 67,000 lines in length

in fact I can recreate (and alleviate, if not solve) the problem by copying the AccountingApi file into my own project and change the namespace to the same as the one being used to access the class

at first it has the same issue: even within the same namespace, the class cannot be resolved

![image](https://user-images.githubusercontent.com/1817370/83381911-406f4280-a425-11ea-95d3-ab54ddbfe209.png)

but then if I remove methods, _reducing the file size_, I reach a point where suddenly the class now CAN be resolved

![image](https://user-images.githubusercontent.com/1817370/83381822-07cf6900-a425-11ea-9885-8483eb73594f.png)

I have attached screenshots to hopefully help illustrate this phenomenon - first with the class unresolved at 67,000 lines and then successfully resolved at 63,000 lines - it does not matter if methods are removed from the beginning or the end of the class

I would suggest perhaps moving some of these methods out into a trait, or even splitting this class into new child classes

**Comment by marekfri** [comment] 2020-06-23 05:47
I can confirm. I have this same issue in PHPStorm IDE. All the other classes are recognized correctly, just this one is missing.

**Comment by SidneyAllen** [comment] 2020-06-24 04:35
@marekfri @mmehmet @chirag2324 

I've reduced the total lines to 58k for the AccountingAPI file in version 2.0.5

**Comment by pancheke** [comment] 2020-07-01 14:41
@marekfri @mmehmet @chirag2324 

In PHPStorm, I fixed this issue by adding the following [custom property](https://www.jetbrains.com/help/phpstorm/tuning-the-ide.html#common-platform-properties) and then invalidating the cache:

`idea.max.intellisense.filesize=3000`
